# Generated by Django 5.0.7 on 2025-04-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=255),
        ),
    ]
