# Generated by Django 5.0.7 on 2025-04-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todo_options_alter_todo_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at']},
        ),
    ]
