# Generated by Django 5.0.7 on 2025-04-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_todo_updated_at_alter_todo_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
    ]
